'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Share2,
  Copy,
  FileJson,
  FileText,
  Link2,
  Check,
  X,
  Download,
} from 'lucide-react';
import type { AnalysisResult } from '@/lib/types';
import { useToast } from './Toast';

interface Props {
  result: AnalysisResult | null;
  code: string;
  language: string;
}

export default function ShareExport({ result, code, language }: Props) {
  const [open, setOpen] = useState(false);
  const { addToast } = useToast();

  if (!result) return null;

  const copyToClipboard = async (text: string, label: string) => {
    try {
      await navigator.clipboard.writeText(text);
      addToast(`${label} copied to clipboard`, 'success');
      setOpen(false);
    } catch {
      addToast('Failed to copy to clipboard', 'error');
    }
  };

  const handleCopyMarkdown = () => {
    const md = `## Code Complexity Analysis

**Time Complexity:** ${result.time_complexity} (${result.time_label})
**Space Complexity:** ${result.space_complexity} (${result.space_label})

### Analysis
${result.explanation}

### Case Analysis
| Case | Complexity | Description |
|------|-----------|-------------|
| Best | ${result.cases.best.notation} | ${result.cases.best.description} |
| Average | ${result.cases.average.notation} | ${result.cases.average.description} |
| Worst | ${result.cases.worst.notation} | ${result.cases.worst.description} |

### Code Breakdown
${result.step_by_step.map((s) => `${s.step}. **Line ${s.line}**: ${s.description} — \`${s.complexity}\``).join('\n')}

### Optimization Suggestions
${result.suggestions.map((s) => `- **${s.title}** ${s.impact ? `(${s.impact})` : ''}: ${s.description}`).join('\n')}

---
*Generated by Algo Scope*`;

    copyToClipboard(md, 'Markdown');
  };

  const handleCopyJSON = () => {
    const json = JSON.stringify(result, null, 2);
    copyToClipboard(json, 'JSON');
  };

  const handleCopyShareLink = () => {
    try {
      const payload = JSON.stringify({ language, code: code.slice(0, 5000) });
      const encoded = btoa(unescape(encodeURIComponent(payload)));
      const url = `${window.location.origin}?share=${encoded}`;
      copyToClipboard(url, 'Share link');
    } catch {
      addToast('Code too long to share via link', 'error');
    }
  };

  const handleCopySummary = () => {
    const summary = `⚡ Code Complexity: ${result.time_complexity} (${result.time_label}) | Space: ${result.space_complexity} (${result.space_label})
${result.explanation}`;
    copyToClipboard(summary, 'Summary');
  };

  const actions = [
    {
      id: 'summary',
      icon: <Copy size={16} />,
      label: 'Copy Summary',
      description: 'Quick text summary',
      action: handleCopySummary,
    },
    {
      id: 'markdown',
      icon: <FileText size={16} />,
      label: 'Copy as Markdown',
      description: 'Full formatted report',
      action: handleCopyMarkdown,
    },
    {
      id: 'json',
      icon: <FileJson size={16} />,
      label: 'Copy as JSON',
      description: 'Raw analysis data',
      action: handleCopyJSON,
    },
    {
      id: 'link',
      icon: <Link2 size={16} />,
      label: 'Copy Share Link',
      description: 'Shareable URL with code',
      action: handleCopyShareLink,
    },
  ];

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 rounded-lg border border-border bg-surface-1 px-3 py-1.5 text-xs font-medium text-text-secondary transition-all hover:border-accent/40 hover:bg-surface-2 hover:text-text-primary"
      >
        <Share2 size={13} />
        Share
      </button>

      <AnimatePresence>
        {open && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setOpen(false)}
              className="fixed inset-0 z-40"
            />
            <motion.div
              initial={{ opacity: 0, y: -4, scale: 0.97 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: -4, scale: 0.97 }}
              transition={{ duration: 0.15 }}
              className="absolute right-0 top-full z-50 mt-2 w-64 overflow-hidden rounded-xl border border-border bg-surface-1 shadow-xl shadow-black/5 dark:shadow-black/20"
            >
              <div className="p-1.5">
                {actions.map((action) => (
                  <button
                    key={action.id}
                    onClick={action.action}
                    className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors hover:bg-surface-2"
                  >
                    <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-surface-2 text-text-tertiary">
                      {action.icon}
                    </span>
                    <div>
                      <div className="text-sm font-medium text-text-primary">
                        {action.label}
                      </div>
                      <div className="text-[10px] text-text-tertiary">
                        {action.description}
                      </div>
                    </div>
                  </button>
                ))}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
}
